version: '3.9'

networks:
  machine_service_network:

services:
  machine_service:
    build:
      context: ./machine_service
    networks:
      - machine_service_network
    volumes:
      - ./machine_service/:/app
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres:latest
    networks:
      - machine_service_network
    restart: always
    container_name: postgres
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - "5431-5432"

  redis:
    image: redis:latest
    networks:
      - machine_service_network
    restart: always
    ports:
      - "6379:6379"


  celery_worker:
    build:
      context: ./machine_service
    networks:
      - machine_service_network
    command: celery -A machine_service worker -l info
    volumes:
      - ./machine_service:/app
    env_file:
      - ./.env
    depends_on:
      - redis
      - db
    links:
      - redis:redis

  celery_beat:
    build:
      context: ./machine_service
    networks:
      - machine_service_network
    command: celery -A machine_service beat -l INFO
    volumes:
      - ./machine_service:/app
    env_file:
      - ./.env
    depends_on:
      - redis
      - db
    links:
      - redis:redis

volumes:
  postgres_volume:
