# Generated by Django 5.1 on 2024-08-22 14:01

import backend.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255, verbose_name='Город')),
                ('state', models.CharField(max_length=255, verbose_name='Штат')),
                ('zip_code', models.CharField(max_length=10, unique=True, verbose_name='Почтовый индекс (zip),')),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='Широта')),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='Долгота')),
            ],
            options={
                'verbose_name': 'Локация',
                'verbose_name_plural': 'Список локаций',
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)], verbose_name='Вес груза')),
                ('description', models.CharField(max_length=500, verbose_name='Описание')),
                ('delivery_pick_up', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_pick_up_cargo', to='backend.location', verbose_name='Локация доставка груза')),
                ('location_pick_up', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_pick_up_cargo', to='backend.location', verbose_name='Локация самовывоза')),
            ],
            options={
                'verbose_name': 'Груз',
                'verbose_name_plural': 'Список грузов',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('unique_number', models.CharField(max_length=5, unique=True, validators=[backend.validators.validate_unique_number], verbose_name='Уникальный номер')),
                ('load_capacity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)], verbose_name='Грузоподъёмность')),
                ('location', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='car', to='backend.location', verbose_name='Текущая локация')),
            ],
            options={
                'verbose_name': 'Машины',
                'verbose_name_plural': 'Список машин',
            },
        ),
    ]
